from collections.abc import Callable, Hashable
from typing import Any, Generic, TypeVar

_T = TypeVar("_T")
_Validator = Callable[[_T], bool]
_Updater = Callable[..., _T]
_WatchCallback = Callable[[Hashable, "Atom[_T]", _T, _T], None]
_SubscriptionCallback = Callable[[_T, _T], None]
_Unsubscribe = Callable[[], None]

VALIDATION_ERROR_MESSAGE: str
__version__: str

class Atom(Generic[_T]):
    def __init__(self, value: _T, *, validator: _Validator[_T] | None = ...) -> None: ...
    @property
    def value(self) -> _T: ...
    @property
    def validator(self) -> _Validator[_T] | None: ...
    def deref(self) -> _T: ...
    def reset(self, new_value: _T) -> _T: ...
    def reset_vals(self, new_value: _T) -> tuple[_T, _T]: ...
    def swap(self, function: _Updater[_T], *args: Any) -> _T: ...
    def swap_vals(self, function: _Updater[_T], *args: Any) -> tuple[_T, _T]: ...
    def compare_and_set(self, expected: _T, new_value: _T) -> bool: ...
    def add_watch(self, key: Hashable, callback: _WatchCallback[_T]) -> Atom[_T]: ...
    def remove_watch(self, key: Hashable) -> _WatchCallback[_T] | None: ...
    def subscribe(
        self,
        callback: _SubscriptionCallback[_T],
        *,
        fire_immediately: bool = ...,
    ) -> _Unsubscribe: ...
    def get_validator(self) -> _Validator[_T] | None: ...
    def set_validator(self, validator: _Validator[_T] | None) -> Atom[_T]: ...

def atom(value: _T, validator: _Validator[_T] | None = ...) -> Atom[_T]: ...
def is_atom(value: object) -> bool: ...
def deref(reference: Atom[_T]) -> _T: ...
def reset(reference: Atom[_T], new_value: _T) -> _T: ...
def reset_vals(reference: Atom[_T], new_value: _T) -> tuple[_T, _T]: ...
def swap(reference: Atom[_T], function: _Updater[_T], *args: Any) -> _T: ...
def swap_vals(reference: Atom[_T], function: _Updater[_T], *args: Any) -> tuple[_T, _T]: ...
def compare_and_set(reference: Atom[_T], expected: _T, new_value: _T) -> bool: ...
def add_watch(reference: Atom[_T], key: Hashable, callback: _WatchCallback[_T]) -> Atom[_T]: ...
def remove_watch(reference: Atom[_T], key: Hashable) -> _WatchCallback[_T] | None: ...
def subscribe(
    reference: Atom[_T],
    callback: _SubscriptionCallback[_T],
    *,
    fire_immediately: bool = ...,
) -> _Unsubscribe: ...
def get_validator(reference: Atom[_T]) -> _Validator[_T] | None: ...
def set_validator(reference: Atom[_T], validator: _Validator[_T] | None) -> Atom[_T]: ...
